FROM golang:1.22.5-alpine AS build

WORKDIR /app

COPY devices/go.mod devices/go.sum ./

RUN go mod download

COPY devices/ .

RUN go build -o main .

FROM alpine:latest

WORKDIR /root/

COPY --from=build /app/main .

EXPOSE 7001

CMD ["./main"]
