FROM golang:1.22.5 AS build

WORKDIR /app

COPY go.mod go.sum ./

RUN go mod download

COPY . .

RUN go build -o main .

FROM gcr.io/distroless/base-debian11

COPY --from=build /app/main /main

CMD ["/main"]
