version: '3.8'

services:
  app:
    image: users_server:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - RABBITMQ_URI=amqp://rabbitmq:5672
      - REDIS_URI=redis:6379
    depends_on:
      - redis
      - rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
